=== MikhailGlushko/UniverEpamJava/Lab8(28.11.2017)/src/main/resources/tariff.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="tariff">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="plan" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="operator-name">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="Life"/>
                    <xs:enumeration value="Kievstar"/>
                    <xs:enumeration value="Vodafone"/>
                    <xs:enumeration value="Beeline"/>
                    <xs:enumeration value="Utel"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element type="priceType" name="payroll"/>
              <xs:element name="call-prices">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="priceType" name="inside-net-calls"/>
                    <xs:element type="priceType" name="outside-net-calls"/>
                    <xs:element type="priceType" name="stationary-phone-calls"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element type="priceType" name="sms-price"/>
              <xs:element name="parameters">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="favourite-number" minOccurs="0">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="priceType">
                            <xs:attribute name="numbers-amount" use="required">
                              <xs:simpleType>
                                <xs:restriction base="xs:double">
                                  <xs:minInclusive value="0"/>
                                  <xs:maxInclusive value="10"/>
                                </xs:restriction>
                              </xs:simpleType>
                            </xs:attribute>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="billing">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="Second"/>
                          <xs:enumeration value="Minute"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element type="priceType" name="activation-price"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
            <xs:attribute name="planID" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:int">
                  <xs:pattern value="[0-9]{8}"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="planUniqueID">
      <xs:selector xpath="plan"/>
      <xs:field xpath="@planID"/>
    </xs:unique>
  </xs:element>
  <xs:simpleType name="priceType">
    <xs:restriction base="xs:double">
      <xs:minInclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== MikhailGlushko/UniverEpamJava/Lab8(28.11.2017)/src/main/resources/tariff.xml
<?xml version="1.0" encoding="UTF-8" ?>
<tariff xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="tariff.xsd">
    <plan name="Simple" planID="12345678">
        <operator-name>Life</operator-name>
        <payroll>50</payroll>
        <call-prices>
            <inside-net-calls>0</inside-net-calls>
            <outside-net-calls>5</outside-net-calls>
            <stationary-phone-calls>7</stationary-phone-calls>
        </call-prices>
        <sms-price>1</sms-price>
        <parameters>
            <favourite-number numbers-amount="4">5</favourite-number>
            <billing>Minute</billing>
            <activation-price>10</activation-price>
        </parameters>
    </plan>
    <plan name="VIP" planID="03587964">
        <operator-name>Kievstar</operator-name>
        <payroll>100</payroll>
        <call-prices>
            <inside-net-calls>5</inside-net-calls>
            <outside-net-calls>10</outside-net-calls>
            <stationary-phone-calls>15</stationary-phone-calls>
        </call-prices>
        <sms-price>3</sms-price>
        <parameters>
            <favourite-number numbers-amount="10">10</favourite-number>
            <billing>Second</billing>
            <activation-price>50</activation-price>
        </parameters>
    </plan>
    <plan name="Vodafone RED XS" planID="12345679">
        <operator-name>Vodafone</operator-name>
        <payroll>50</payroll>
        <call-prices>
            <inside-net-calls>0</inside-net-calls>
            <outside-net-calls>0.50</outside-net-calls>
            <stationary-phone-calls>2</stationary-phone-calls>
        </call-prices>
        <sms-price>0.50</sms-price>
        <parameters>
            <billing>Second</billing>
            <activation-price>70</activation-price>
        </parameters>
    </plan>
</tariff>
